// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace IPList
{
	public partial class CTextField : NSTextField
	{
        public static ushort KeyCode;

		public CTextField (IntPtr handle) : base (handle)
		{
		}

        // part of a stupid h ack to get a keydown event for textfields
        public override void KeyUp(NSEvent theEvent)
        {
            base.KeyUp(theEvent);
            KeyCode = theEvent.KeyCode;
        }
    }
}
